


header = {
!   "main":{ # Die main -parameter müssen vorhanden sein!
!       "make":"",
!       "model":"",
!       "image_width":"",
!       "datetime":"",
!       "latitude":"",
!       "longitude":"",
!       "rel_altitude":"",
!       "pitch":"",
!       "roll":"",
!       "yaw":"",
        "current_camera":"thermal",
        "current_image":"main",
        }
    "general":{
        ""
    }
        
!   "image":{
        "main":{
            "band": "LWIR"
            "width":"",
            "height":"",
            "bitdepth":"",
            "channels":"",
            "orientation":"",
            "resolution":"",
            "index":1,
            "camera":(0,1),
            },
        "thumbnail":{
            "width":"",
            "height":"",
            "bitdepth":"",
            "channels":"",
            "orientation":"",
            "resolution":"",
            "index":0,
            "camera":(0,1),
            
            },
        "raw_thermal":{
            "band":""
            "width":"",
            "height":"",
            "bitdepth":"",
            "channels":"",
            "orientation":"",
            "resolution":"",
            "index":2,
            "camera":0,
        },
        "raw_vis":{
            "width":"",
            "height":"",
            "bitdepth":"",
            "channels":"",
            "orientation":"",
            "resolution":"",
            "index":3,
            "camera":1,
        },
    "cameras":{
        "thermal":{
            "band":"LWIR",
            "centralwavelength":"",
            "wavelengthfwhm":"",
            "emissivity":"",
            "R1":"",
            "B":"",
            "F":"",
            "tlineargain":"",
            "isnormalized":"",
            "relativeHumidity":"",
            "objectDistance":"",
            "reflectedApparentTemperature":"",
            "IRWindowTemperature":"",
            "IRWindowTransmission":"",
            "atmosphericTransAlpha1":"",
            "atmosphericTransAlpha2":"",
            "atmosphericTransBeta1":"",
            "atmosphericTransBeta2":"",
            "atmosphericTransX":"",
            "FocalPlaneXResolution":"",
            "FocalPlaneYResolution":"",
            "pitch":"",
            "roll":"",
            "yaw":"",
            "FfcState":"",
            "FfcDesired":"",
            "FrameCount":"",
            "FrameRate":"",

        }
        "vis":{
            "exposureProgram":"",
            "exposureMode":"",
            "exposureTime":"",
            "exposureBiasValue":"",
            "ISOSpeed":"",
            "ISOSpeedRatings":"",
            "ShutterSpeedValue":"",
            "MeteringMode":"",
            "SensingMethod":"",
            "ApertureValue":"",
            "MaxApertureValue":"",
            "FNumber":"",
            "LightSource":"",
            "Flash":"",
            "WhiteBalance":"",
            "GainControl":"",
            "Contrast":"",
            "Saturation":"",
            "Sharpness":"",
            "FocalLength":"",
            "FocalLengthIn35mmFilm":"",
            "DigitalZoomRatio":"",
            "pitch":"",
            "roll":"",
            "yaw":"",
        }
    },
!   "file":{
        "path":"",
        "name":"",
        "extension":"",
        "modified":"",
        "created":"",
        },
    "time":{
        "DateTime":"",
        "Date":"",
        "Time":"",
        "DateTimeOriginal":"",
        "DateTimeDigitized":"",
        "modified":"",
        "created":"",
        }
!   "position":{
!       "latitude":"",
!       "longitude":"",
!       "altitude":"",
!       "rel_altitude":"",
!       "cam_pitch":"",
!       "cam_roll":"",
!       "cam_yaw":"",
        "UTM_X",
        "UTM_Y",
        "UTM Zone",
        "uav_pitch":"",
        "uav_roll":"",
        "uav_yaw":"",
        "":"",
        }
    
    }